### ISSUE TITLE
Translate data into JSON

### ISSUE THREAD

**Issue by xxnatc** [sabbyt/house-of-gift-cards#15]
Put [our data spreadsheet](https://docs.google.com/spreadsheets/d/1AnHvRfAuwX13qb0LhncMGOyHB82sy2i7Sz4fwmBJwV8/edit#gid=0) into JSON format! See column names at #14 .

**Comment by sabbyt** [comment]
Done! Can be found at: https://github.com/sabbyt/house-of-gift-cards/tree/day-one-JSON-data
