### ISSUE TITLE
TO DO ON MONDAY

### ISSUE THREAD

**Issue by sabbyt** [sabbyt/house-of-gift-cards#36]
- connect all the .html files into one scrolling index.html page.
- router.js formatting
- correct hyperlinks: buttons, nav bar etc.
- deploy to interwebz

follow-ups: #57, #62

**Comment by xxnatc** [comment]
Firebase deployment config for pushstate:

```
"rewrites": [ {
  "source": "**",
  "destination": "/index.html"
} ]
```

The above config redirects any file in any folder to `/index.html`.
(from Firebase hosting docs [here](https://www.firebase.com/docs/hosting/guide/full-config.html#section-advanced-properties) and [here](https://www.firebase.com/docs/hosting/guide/url-redirects-rewrites.html))
