### ISSUE TITLE
Request page - list & grid views

### ISSUE THREAD

**Issue by sabbyt** [sabbyt/house-of-gift-cards#5]
##### User Stories
- As a user, I want requests to have information about the requester and a story about their struggle, so I can pick who I would like to donate to.
- As a developer, I want to declare templates for gift requests, so that I can display the requests easier. 
##### Features
- list view and grid view for requests
- pop up module to display full story on click
- use separate templates to populate list and grid views

Next step: filtering (#4)

**Comment by scarney3** [comment]
List view is now rendering on the page.

**Comment by xxnatc** [comment]
List/grid view display and filtering both work! (See #69 for details)
