### ISSUE TITLE
Create admin page - claim statuses for distribution

### ISSUE THREAD

**Issue by sabbyt** [sabbyt/house-of-gift-cards#9]
As an admin, I want a page where we can easily retrieve claim statuses to distribute gift cards.
- Retrieve data from request table.
- Display in list format.
- Sortable by status of claimed/sent.

**Comment by xxnatc** [comment]
- [x] Retrieve data from request table, sorted by `claimed_dt`
- [x] Display in list format
- [x] Update status in Firebase on click
- [x] Sortable by status of claimed/sent

**Comment by xxnatc** [comment]
Admin page now sortable by a few properties, and/or display only ALL/CLAIMED/SENT requests.
